import config from '@qlik/oxfmt-config';
import { defineConfig } from 'oxfmt';

export default defineConfig({
  ...config,
  endOfLine: 'lf',
  singleQuote: true,
  trailingComma: 'es5',
  ignorePatterns: [
    // generated by `pnpm --filter @scriptappy/schema generate` — JSON.stringify output has no
    // trailing newline; formatting it here would create a permanent diff against the generator
    'packages/scriptappy-schema/schema.json',
    // generated by `pnpm --filter @scriptappy/schema generate` — markdown tables are rendered
    // with fixed column widths that don't match oxfmt's table formatting
    'packages/scriptappy-schema/specification.md',
    // generated by `pnpm --filter @scriptappy/to-dts spec` (from-jsdoc) — JSON.stringify output
    // has no trailing newline; formatting it here would create a permanent diff against the generator
    'packages/to-dts/scriptappy.json',
  ],
});
