version: 2.1

aliases:
  - &restore_yarn_cache
    keys:
      - v2-yarn-4-deps-{{ checksum "yarn.lock" }}
      - v2-yarn-4-deps-
  - &save_yarn_cache
    paths:
      - ~/.yarn/berry/cache
      - .yarn/install-state.gz
    key: v2-yarn-4-deps-{{ checksum "yarn.lock" }}

setup: &setup
  working_directory: ~/scriptappy
  docker:
    - image: cimg/node:22.12.0-browsers

jobs:
  build:
    <<: *setup
    steps:
      - checkout
      - restore_cache: *restore_yarn_cache
      - run: corepack enable
      - run: yarn install --immutable
      - save_cache: *save_yarn_cache
      - run: yarn run lint
      - run: yarn run test
